### ISSUE TITLE
[Feature Request] Main hand reverse render

### ISSUE THREAD

**Issue by sscards55** [iChun/BackTools#1]
Now that Minecraft has added the ability to choose left or right as your main hand, I think it would be nice to render the Backtool item backwards if you are left handed.
![2017-04-01_14 46 52](https://cloud.githubusercontent.com/assets/5591207/24582756/a5521f94-16eb-11e7-8ce8-047ecaece805.png)
Right now the way the swords render if you're left handed seems unusual.

**Comment by iChun** [comment]
No no leave it open. I'll try and sort this out when I can.

**Comment by iChun** [comment]
Will be resolved in the 1.14 version of the mod.
