### ISSUE TITLE
[recommendation] add dedicated json format for adding and removing items to black/white list

### ISSUE THREAD

**Issue by ghost** [iChun/BackTools#11]
How do you blacklist items or classes?

I've added ItemTool to the blacklist, yet tools still show up.

A dedicated regular .json, for adding/removing specific items, would be great.

Such as:

Add: { minecraft:shield }

Remove: { minecraft:pickaxe }

**Comment by iChun** [comment]
JSONs are unnecessary for simple configs like these. Most users do not change configs of mods outside of the box. 

You cannot blacklist or whitelist classes, only the registered names for the item. The configs have options for either and their comments should tell you how to use them.

**Comment by ghost** [comment]
> general {
>     # backtools.config.prop.blacklistedItemClasses.comment [default: ]
>     S:blacklistedItemClasses <
> 
>      >
> }

That's the 1.12.2 config. Where does it say use registered names? It says Item Classes.

How do you use this config, then? Because " their comments should tell you how to use them" isn't exactly true, as multiple people have mentioned problems understanding formatting.

**Comment by iChun** [comment]
1.12.2 is no longer supported. I'm referring to the builds of the mod on
1.16 and later. These configs use the full class path of the class so
something like net.minecraft.item.ItemTool or something like that. One per
line.
