### ISSUE TITLE
[1.16.5-10.1.0] Issue when in an horizontal stance

### ISSUE THREAD

**Issue by Klinker195** [iChun/BackTools#12]
Hi iChun, I'm having an issue with the last version of your mod, pratically the back tool starts to spin in loop every time the player is in an horizontal stance.
Example conditions that cause the problem:

- Flying
- Swimming
- Being prone using a trapdoor

I was using the mod on a private server, I'll remove it temporarily. I hope you solve the problem soon, thank you for your work!

Example GIF of the problem:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/64706581/110237391-190d4f00-7f3c-11eb-970a-edca21ab382f.gif)

**Comment by iChun** [comment]
Thanks for the report! This is however just an easter egg, no worries. You can disable this in the iChunUtil client config. https://github.com/iChun/BackTools/issues/10
