### ISSUE TITLE
The tools are staying on the back even though I removed it

### ISSUE THREAD

**Issue by Ninezel** [iChun/BackTools#13]
I still of said weapons and shields on my back even though I removed them from my inventory.

**Comment by manmaed** [comment]
is just a Visual Tool it dosn't keep any track of tools

**Comment by candied-apple** [comment]
But it should

**Comment by iChun** [comment]
It's not worth the additional overhead of having to constantly scan the player's inventory just to see if the item on the back is still in your inventory. There are a lot of other mods out there that will could make use of those resources for more beneficial reasons.
