### ISSUE TITLE
shield inside player model + tool spinning while crawling

### ISSUE THREAD

**Issue by Wedge1453** [iChun/BackTools#14]
![2021-03-19_11 58 21](https://user-images.githubusercontent.com/76813383/111777704-eb1cf880-88b3-11eb-9ba8-70018e820d5f.png)

**Comment by Wedge1453** [comment]
![2021-03-19_12 08 05](https://user-images.githubusercontent.com/76813383/111777913-346d4800-88b4-11eb-8353-e5a06ec61de1.png)

**Comment by iChun** [comment]
The shield is a bit of an odd model and was very difficult to fit and scale
properly on the model. I think it was supposed to be disabled by default
but I may have removed it from the config.

The spinning tools when crawling is an Easter egg. Disable it in
iChunUtil's client config.

**Comment by MrKashew** [comment]
Will disabling shield model in config disable modded shields as well (if they use same model), or will these have to be added manually

**Comment by iChun** [comment]
Sorry bout the late reply, I can't give a definite yes/no answer, it depends on how the mod adds their shields.
