### ISSUE TITLE
[Question/Issue] No Inventory slots for Tools

### ISSUE THREAD

**Issue by ZaneDragonBorn** [iChun/BackTools#15]
I don't see any slots for the tools in my Inventory. Is there another way to view it?
![image](https://user-images.githubusercontent.com/68198648/112398417-84944200-8cda-11eb-836f-aadb585b07c8.png)

**Comment by iChun** [comment]
BackTools is a client-sided mod. It's only an aesthetics mod which picks what it thinks was the last tool you held and puts it on your back, so there is no slot for it since that will require the mod communicate with the server and back.
