### ISSUE TITLE
Offhand bug

### ISSUE THREAD

**Issue by sscards55** [iChun/BackTools#2]
If you change your item to the off hand Backtools still renders it even though it is currently in your offhand.
![2017-04-01_15 00 27](https://cloud.githubusercontent.com/assets/5591207/24582806/7f199ed2-16ec-11e7-820f-d57edbdebd07.png)

**Comment by iChun** [comment]
Nooooo don't close them

**Comment by iChun** [comment]
Will be fixed in the 1.14 version of the mod
