### ISSUE TITLE
Shield is scaled too big, so much so it goes inside armor

### ISSUE THREAD

**Issue by MuffinElZangano** [iChun/BackTools#20]
Not sure if it's only me, but the shield is waaay too big, even the vanilla one, is this an error or can i config this?

**Comment by iChun** [comment]
Feel free to disable it in the config. Just add a "minecraft:shield" entry and that should be fine.

You can see from here it was meant to be disabled but my chat (I was streaming the development) suggested I leave it enabled.... well I'll be disabling it next update, heh. https://github.com/iChun/BackTools/blob/1.16/src/main/java/me/ichun/mods/backtools/common/core/Config.java#L24
