### ISSUE TITLE
Shown Iron Shovel when I don't have it

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [iChun/BackTools#4]
![image](https://user-images.githubusercontent.com/25037295/41663645-7bd89a68-74d6-11e8-9eaa-81b47691b542.png)

**Comment by sscards55** [comment]
Did you use to have that item in your inventory? BackTools only checks whether you had the item in your hand previously but not if it's in your inventory.

**Comment by Pythonic-Rainbow** [comment]
I think so. anyways if thats intended then I will close it.
