### ISSUE TITLE
Crash in 1.16.3

### ISSUE THREAD

**Issue by UnRealDinnerbone** [iChun/BackTools#6]
Backtools causes client to crash after join multiplayer server and looking at player https://pste.ch/ziyotixiwu.pl

**Comment by BugmanBugman** [comment]
By any chance does this happen with AdoptOpenJDK Java 8? I think Backtools just has a compatiblity error with Java 14 for the time being.

**Comment by UnRealDinnerbone** [comment]
yha it does not happen in Java 8

**Comment by BugmanBugman** [comment]
Yeah I think this mod just doesn’t work with Java 11+ versions

**Comment by jupjohn** [comment]
Also confirmed not working with AdoptOpenJDK 11.

**Comment by iChun** [comment]
Should be fixed in 10.1.0. Thanks for the reports and ichttt for helping me resolve this.
