### ISSUE TITLE
Incompatibility with AdoptOpenJDK 14

### ISSUE THREAD

**Issue by BugmanBugman** [iChun/BackTools#7]
https://hastebin.com/latuyigohe.mccrash

**Comment by BugmanBugman** [comment]
Did some testing, this only happen when you use Java 14. On Java 8, nothing happens.

**Comment by BugmanBugman** [comment]
The crash happens on Java 14 when your paper doll shows up in the corner while you have a backtool.

**Comment by Bernasss12** [comment]
I can confirm this also happens with OpenJDK 11
[Log](https://paste.ee/p/u5XCi)

It was my fault to have my home set to JDK 11 though.

**Comment by phit** [comment]
still an issue https://gist.github.com/phit/42e1e17e27019285586010ee3efb46b4

**Comment by BugmanBugman** [comment]
can confirm

**Comment by iChun** [comment]
Should be fixed in 10.1.0. Thanks for the reports and ichttt for helping me resolve this.
